/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#e8f0ff',
          100: '#d4e4ff',
          200: '#b8d4ff',
          300: '#8cb8ff',
          400: '#5c94ff',
          500: '#165dff',
          600: '#0e4bdb',
          700: '#0b3ab1',
          800: '#0a2f8f',
          900: '#092873',
        },
        brand: {
          50: '#e8f0ff',
          100: '#d4e4ff',
          500: '#165dff',
          600: '#0e4bdb',
          700: '#0b3ab1',
        },
        surface: {
          0: '#ffffff',
          50: '#f7f8fa',
          100: '#f2f3f5',
          200: '#e5e6eb',
          300: '#c9cdd4',
          400: '#86909c',
          500: '#4e5969',
          600: '#1d2129',
          700: '#171a1f',
          800: '#0f1216',
          900: '#000000',
        },
        semantic: {
          success: '#00b42a',
          'success-light': '#e8ffea',
          'success-dark': '#009a29',
          warning: '#ff7d00',
          'warning-light': '#fff7e8',
          'warning-dark': '#d25f00',
          danger: '#f53f3f',
          'danger-light': '#ffece8',
          'danger-dark': '#cb2634',
          info: '#165dff',
          'info-light': '#e8f0ff',
          'info-dark': '#0e4bdb',
        },
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          'PingFang SC',
          'Hiragino Sans GB',
          'Microsoft YaHei',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '1.5' }],
        xs: ['12px', { lineHeight: '1.5' }],
        sm: ['13px', { lineHeight: '1.5' }],
        base: ['14px', { lineHeight: '1.5715' }],
        lg: ['16px', { lineHeight: '1.5' }],
        xl: ['20px', { lineHeight: '1.4' }],
        '2xl': ['24px', { lineHeight: '1.333' }],
        '3xl': ['28px', { lineHeight: '1.286' }],
      },
      spacing: {
        '4.5': '1.125rem',
        '13': '3.25rem',
        '15': '3.75rem',
      },
      borderRadius: {
        '4': '4px',
        '6': '6px',
        '8': '8px',
        '10': '10px',
        '12': '12px',
      },
      boxShadow: {
        'card': '0 1px 2px rgba(0,0,0,0.03)',
        'card-hover': '0 4px 10px rgba(0,0,0,0.06)',
        'modal': '0 8px 40px rgba(0,0,0,0.12)',
        'dropdown': '0 4px 10px rgba(0,0,0,0.1)',
        'sticky': '0 -2px 8px rgba(0,0,0,0.04)',
        '1': '0 1px 2px rgba(0,0,0,0.03)',
        '2': '0 2px 8px rgba(0,0,0,0.06)',
        '3': '0 4px 16px rgba(0,0,0,0.08)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(6px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-down': {
          from: { opacity: '0', transform: 'translateY(-6px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.97)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'slide-up': {
          from: { transform: 'translateY(100%)' },
          to: { transform: 'translateY(0)' },
        },
        'slide-in-right': {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        'shimmer': {
          from: { backgroundPosition: '-200% 0' },
          to: { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-out both',
        'fade-in-up': 'fade-in-up 0.25s cubic-bezier(0.4,0,0.2,1) both',
        'fade-in-down': 'fade-in-down 0.2s ease-out both',
        'scale-in': 'scale-in 0.2s cubic-bezier(0.4,0,0.2,1) both',
        'slide-up': 'slide-up 0.25s cubic-bezier(0.4,0,0.2,1) both',
        'slide-in-right': 'slide-in-right 0.25s cubic-bezier(0.4,0,0.2,1) both',
        'shimmer': 'shimmer 1.5s linear infinite',
      },
      transitionDuration: {
        '150': '150ms',
        '250': '250ms',
      },
      transitionTimingFunction: {
        'vc': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
};
